-- Initialize site_settings table with default values
-- Run this if your site_settings table is empty

INSERT INTO `site_settings` (`setting_key`, `setting_value`, `setting_type`, `updated_at`) VALUES
('site_name', 'Zuba Online Market', 'text', NOW()),
('site_tagline', 'Your One-Stop Marketplace', 'text', NOW()),
('site_email', 'info@zubamarket.com', 'text', NOW()),
('site_phone', '+250788000000', 'text', NOW()),
('site_address', 'Kigali, Rwanda', 'text', NOW()),
('site_logo', '', 'text', NOW()),
('site_favicon', '', 'text', NOW()),
('currency', 'RWF', 'text', NOW()),
('currency_symbol', 'FRw', 'text', NOW()),
('tax_rate', '0', 'number', NOW()),
('shipping_fee', '0', 'number', NOW()),
('items_per_page', '12', 'number', NOW()),
('enable_reviews', '1', 'boolean', NOW()),
('enable_wishlist', '1', 'boolean', NOW()),
('enable_products', '1', 'boolean', NOW()),
('enable_properties', '1', 'boolean', NOW()),
('enable_vehicles', '1', 'boolean', NOW()),
('maintenance_mode', '0', 'boolean', NOW()),
('primary_color', '#f97316', 'text', NOW()),
('secondary_color', '#1a1a2e', 'text', NOW()),
('header_background', '#ffffff', 'text', NOW()),
('support_email', 'support@zubamarket.com', 'text', NOW()),
('support_phone', '+250788000000', 'text', NOW()),
('facebook_url', '', 'text', NOW()),
('twitter_url', '', 'text', NOW()),
('instagram_url', '', 'text', NOW()),
('linkedin_url', '', 'text', NOW()),
('youtube_url', '', 'text', NOW()),
('whatsapp_number', '', 'text', NOW()),
('header_sticky', '1', 'boolean', NOW()),
('show_search_bar', '1', 'boolean', NOW()),
('show_cart_icon', '1', 'boolean', NOW()),
('show_wishlist_icon', '1', 'boolean', NOW()),
('show_user_menu', '1', 'boolean', NOW()),
('show_categories_menu', '1', 'boolean', NOW()),
('header_text_color', '#1a1a2e', 'text', NOW()),
('header_border_color', '#e5e7eb', 'text', NOW()),
('logo_max_width', '150', 'number', NOW()),
('logo_max_height', '50', 'number', NOW()),
('search_placeholder', 'Search products, properties, vehicles...', 'text', NOW()),
('enable_notifications', '1', 'boolean', NOW()),
('show_top_bar', '1', 'boolean', NOW()),
('top_bar_text', 'Free shipping on orders over 50,000 FRw', 'text', NOW()),
('top_bar_background', '#f97316', 'text', NOW()),
('top_bar_text_color', '#ffffff', 'text', NOW())
ON DUPLICATE KEY UPDATE updated_at = NOW();
